version: "3.7"

x-envs: &envs
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: mock_access_key
  AWS_SECRET_ACCESS_KEY: mock_secret_key

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      <<: *envs
      SERVICES: lambda,iam
      PORT_WEB_UI: 8080
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "~/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
